version: '3.8'

services:
  nginx:
    image: nginx
    restart: always
    container_name: "nginx-portfolio-container"
    ports:
      - "8081:80"
    networks:
      portfolio-network:
        ipv4_address: 172.20.0.1
  asp-portfolio:
    image: asp-portfolio-image:latest
    restart: always
    container_name: "asp-portfolio-container"
    depends_on:
      - nginx
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      portfolio-network:
        ipv4_address: 172.20.0.2
  sqlite:
    image: sqlite3
    environment:
      SQL_DATABASE: asp-portfolio
    volumes:
      - ./sqlite:/var/lib/sqlite

networks:
  portfolio-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16